### ISSUE TITLE
Interacting with the contract always fail

### ISSUE THREAD

**Issue by danqulogy** [danqulogy/multi-sign-wallet#1]
```
truffle(development)> instance.approve()
{ Error: Returned error: VM Exception while processing transaction: revert Not an Approver -- Reason given: Not an Approver.
    at XMLHttpRequest._onHttpResponseEnd (C:\Users\Dan White\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\xhr2-cookies\dist\xml-http-request.js:318:1)
    at XMLHttpRequest._setReadyState (C:\Users\Dan White\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\xhr2-cookies\dist\xml-http-request.js:208:1)
    at XMLHttpRequestEventTarget.dispatchEvent (C:\Users\Dan White\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\xhr2-cookies\dist\xml-http-request-event-target.js:34:1)
    at XMLHttpRequest.request.onreadystatechange (C:\Users\Dan White\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\web3\~\web3-providers-http\src\index.js:96:1)
    at C:\Users\Dan White\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-provider\wrapper.js:112:1
    at C:\Users\Dan White\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\web3-eth\~\web3-core-requestmanager\src\index.js:140:1
    at Object.ErrorResponse (C:\Users\Dan White\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\web3-eth\~\web3-core-helpers\src\errors.js:29:1) reason: 'Not an Approver' }
```

**Comment by danqulogy** [comment]
Looking try again with UI facing interactivity as done in the video tutorial I was following
